# Generated by Django 3.2.1 on 2021-10-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='comment',
            field=models.TextField(null=True,
                                   verbose_name='Comment your table add'),
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='comment',
            field=models.TextField(null=True,
                                   verbose_name='Comment your table add'),
        ),
        migrations.AddField(
            model_name='human',
            name='comment',
            field=models.TextField(null=True,
                                   verbose_name='Comment your table add'),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(null=True,
                                   verbose_name='Comment your table add'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='comment',
            field=models.TextField(null=True,
                                   verbose_name='Comment your table add'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.IntegerField(null=True,
                                      verbose_name='Deadline homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='text',
            field=models.TextField(null=True,
                                   verbose_name='Text homework'),
        ),
        migrations.AlterField(
            model_name='homeworkresult',
            name='solution',
            field=models.TextField(null=True,
                                   verbose_name='Homework solution'),
        ),
    ]
