# Generated by Django 3.2.1 on 2021-10-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211024_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkresult',
            name='data_created',
            field=models.DateTimeField(default='2021-10-28 06:20:44'),
        ),
    ]
