# Generated by Django 3.2.1 on 2021-10-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homeworkresult_last_name_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkresult',
            name='data_created',
            field=models.DateTimeField(null=True, verbose_name='Add datatime'),
        ),
    ]
